# Generated by Django 4.2.6 on 2023-10-13 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="owner",
            new_name="author",
        ),
    ]
